name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - name: Ensure SHA pinned actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@b8f9a25a51fe633d9215ac7734854dc11cd299cb

  build_test:
    name: Build & Test
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      with:
        ref: ${{ github.head_ref }} # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
    - name: Get runs.using version
      id: get-runs-using-version
      uses: zgosalvez/github-actions-get-action-runs-using-version@853b59b8486c8a7869ca4fb1735959ac58b32262
    - name: Set up Node
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6
      with:
        node-version: v${{ steps.get-runs-using-version.outputs.version }}
    - name: Cache Node Packages
      id: node-cache
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        path: ~/.npm
        key: node-cache-${{ steps.get-runs-using-version.outputs.prop }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-cache-${{ steps.get-runs-using-version.outputs.prop }}-
          node-cache-
    - name: Get Node packages
      run: npm ci
    - name: Run linter tool
      run: npm run lint
    - name: Prepare
      run: npm run prepare
    - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842
      with:
        commit_message: Apply `npm run prepare` changes
