name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Ensure SHA pinned actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@6124774845927d14c601359ab8138699fa5b70c3

  build_test:
    name: Build & Test
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        ref: ${{ github.head_ref }} # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - name: Get runs.using version
      id: get-runs-using-version
      uses: zgosalvez/github-actions-get-action-runs-using-version@6ded6f570d3957576d469187e5c39d3dda7857ef
    - name: Set up Node
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
      with:
        node-version: v${{ steps.get-runs-using-version.outputs.version }}
    - name: Cache Node Packages
      id: node-cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
      with:
        path: ~/.npm
        key: node-cache-${{ steps.get-runs-using-version.outputs.prop }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-cache-${{ steps.get-runs-using-version.outputs.prop }}-
          node-cache-
    - name: Get Node packages
      run: npm ci
    - name: Run linter tool
      run: npm run lint
    - name: Prepare
      run: npm run prepare
    - uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3
      if: github.event.pull_request.head.repo.full_name == github.repository
      with:
        commit_message: Apply `npm run prepare` changes
