name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Ensure SHA pinned actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@c3a2b64f69b7a1542a68f44d9edbd9ec3fc1455e

  build_test:
    name: Build & Test
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: ${{ github.head_ref }} # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
    - name: Get runs.using version
      id: get-runs-using-version
      uses: zgosalvez/github-actions-get-action-runs-using-version@f3493d1f86a704e7d55716321c448b9eb3de2849
    - name: Set up Node
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
      with:
        node-version: v${{ steps.get-runs-using-version.outputs.version }}
    - name: Cache Node Packages
      id: node-cache
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
      with:
        path: ~/.npm
        key: node-cache-${{ steps.get-runs-using-version.outputs.prop }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-cache-${{ steps.get-runs-using-version.outputs.prop }}-
          node-cache-
    - name: Get Node packages
      run: npm ci
    - name: Run linter tool
      run: npm run lint
    - name: Prepare
      run: npm run prepare
    - uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79
      with:
        commit_message: Apply `npm run prepare` changes
