name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Ensure SHA pinned actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@b35f285b9bb7e80de0967367cee66d3b6d50ceca

  build_test:
    name: Build & Test
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        ref: ${{ github.head_ref }} # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
    - name: Get runs.using version
      id: get-runs-using-version
      uses: zgosalvez/github-actions-get-action-runs-using-version@7e91b33ec663b83a966c937c6267e2d19bc2103b
    - name: Set up Node
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
      with:
        node-version: v${{ steps.get-runs-using-version.outputs.version }}
    - name: Cache Node Packages
      id: node-cache
      uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
      with:
        path: ~/.npm
        key: node-cache-${{ steps.get-runs-using-version.outputs.prop }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-cache-${{ steps.get-runs-using-version.outputs.prop }}-
          node-cache-
    - name: Get Node packages
      run: npm ci
    - name: Run linter tool
      run: npm run lint
    - name: Prepare
      run: npm run prepare
    - uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d
      with:
        commit_message: Apply `npm run prepare` changes
